#include "terminal/file_panel/terminal_file_panel.h"


void TerminalFilePanel::applyPanelStyle()
{
    setStyleSheet(QStringLiteral(
        "#terminalFilePanel { background: #181818; color: rgb(131, 193, 224); }"
        "#terminalFilePanel QLineEdit,"
        "#terminalFilePanel QComboBox {"
        "    background: #181818;"
        "    color: rgb(131, 193, 224);"
        "    border: 1px solid #858585;"
        "    border-radius: 4px;"
        "    padding: 2px 6px;"
        "    min-height: 18px;"
        "}"
        "#terminalFilePanel QComboBox::drop-down { border: none; width: 16px; }"
        "#terminalFilePanel QComboBox QAbstractItemView {"
        "    background: #242424;"
        "    color: #e5eaf3;"
        "    border: 1px solid #4c4d4f;"
        "    selection-background-color: #783041;"
        "}"
        "#terminalFilePanel QCheckBox {"
        "    background: transparent;"
        "    color: rgb(131, 193, 224);"
        "    spacing: 4px;"
        "}"
        "#terminalFilePanel QCheckBox::indicator { width: 12px; height: 12px; }"
        "#terminalFilePanel QLabel#terminalTransferStatusLabel {"
        "    background: transparent;"
        "    color: rgb(131, 193, 224);"
        "    padding: 0 2px;"
        "}"
        "#terminalFilePanel QProgressBar#terminalTransferProgressBar {"
        "    background: #242424;"
        "    border: 1px solid #3a3a3a;"
        "    border-radius: 2px;"
        "}"
        "#terminalFilePanel QProgressBar#terminalTransferProgressBar::chunk {"
        "    background: #5aa6d6;"
        "    border-radius: 1px;"
        "}"
        "#terminalFilePanel QTableWidget {"
        "    background: #181818;"
        "    alternate-background-color: #181818;"
        "    color: rgb(131, 193, 224);"
        "    border: 1px solid #3a3a3a;"
        "    gridline-color: transparent;"
        "    selection-background-color: #783041;"
        "}"
        "#terminalFilePanel QTableWidget::item {"
        "    background: #181818;"
        "    color: rgb(131, 193, 224);"
        "    padding: 3px;"
        "}"
        "#terminalFilePanel QTableWidget::item:selected {"
        "    background: #783041;"
        "    color: #ffffff;"
        "}"
        "#terminalFilePanel QHeaderView::section {"
        "    background: #202020;"
        "    color: rgb(131, 193, 224);"
        "    border: 1px solid #3a3a3a;"
        "    padding: 4px;"
        "}"
        "#terminalFilePanel QToolButton {"
        "    background: transparent;"
        "    border: 1px solid transparent;"
        "    border-radius: 3px;"
        "    color: rgb(131, 193, 224);"
        "    padding: 1px;"
        "}"
        "#terminalFilePanel QToolButton:hover {"
        "    background: #242424;"
        "    border-color: #4c4d4f;"
        "}"
        "#terminalFilePanel QToolButton:disabled { color: #777777; }"));
}
