cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED DESTINATION_FILE OR DESTINATION_FILE STREQUAL "")
    message(FATAL_ERROR "DESTINATION_FILE is required")
endif()

if(DEFINED SOURCE_FILE AND NOT SOURCE_FILE STREQUAL "" AND EXISTS "${SOURCE_FILE}")
    file(COPY_FILE "${SOURCE_FILE}" "${DESTINATION_FILE}" ONLY_IF_DIFFERENT)
else()
    file(REMOVE "${DESTINATION_FILE}")
endif()
