set(SRC_FILES
    src/app/app_runtime.cpp
    src/app/app_runtime_application.cpp
    src/app/app_runtime_common.cpp
    src/app/app_style.cpp
    src/app/app_headless_controller.cpp
    src/app/app_headless_controller_sessions.cpp
    src/app/app_headless_controller_ws.cpp
    src/media/codec/webrtc/airan_codec_adapter.cpp
    src/media/capture/core/airan_capture_frame.cpp
    src/media/capture/core/airan_capture_interface.cpp
    src/media/codec/airan_video_bitrate_profile.cpp
    src/media/codec/airan_video_codec_backend.cpp
    src/media/codec/backends/ffmpeg/codec/ffmpeg_codec_capabilities.cpp
    src/media/codec/backends/ffmpeg/codec/ffmpeg_codec_probe.cpp
    src/media/codec/backends/ffmpeg/codec/ffmpeg_codec_probe_runtime.cpp
    src/media/codec/backends/ffmpeg/codec/ffmpeg_codec_probe_table.cpp
    src/media/codec/backends/ffmpeg/codec/ffmpeg_openh264_option.cpp
    src/media/codec/backends/ffmpeg/codec/ffmpeg_codec_types.cpp
    src/media/codec/backends/ffmpeg/decoder/ffmpeg_video_decoder.cpp
    src/media/codec/backends/ffmpeg/decoder/ffmpeg_video_decoder_config.cpp
    src/media/codec/backends/ffmpeg/decoder/ffmpeg_video_decoder_emit.cpp
    src/media/codec/backends/ffmpeg/encoder/core/ffmpeg_video_encoder.cpp
    src/media/codec/backends/ffmpeg/encoder/core/ffmpeg_video_encoder_config.cpp
    src/media/codec/backends/ffmpeg/encoder/core/ffmpeg_video_encoder_encode.cpp
    src/media/codec/backends/ffmpeg/encoder/core/ffmpeg_video_encoder_input.cpp
    src/media/codec/backends/ffmpeg/encoder/hw/ffmpeg_video_encoder_hw_d3d11.cpp
    src/media/codec/backends/ffmpeg/encoder/hw/ffmpeg_video_encoder_hw_frames.cpp
    src/media/codec/backends/ffmpeg/encoder/hw/ffmpeg_video_encoder_hw_qsv.cpp
    src/media/codec/backends/ffmpeg/encoder/hw/ffmpeg_video_encoder_hw_session.cpp
    src/media/codec/backends/ffmpeg/encoder/util/ffmpeg_encoder_util.cpp
    src/media/codec/backends/ffmpeg/encoder/util/ffmpeg_encoder_util_i420.cpp
    src/media/codec/backends/ffmpeg/encoder/util/ffmpeg_encoder_util_options.cpp
    src/media/codec/backends/ffmpeg/encoder/util/ffmpeg_encoder_util_packet.cpp
    src/media/codec/backends/ffmpeg/encoder/util/ffmpeg_encoder_util_safe.cpp
    src/media/codec/backends/ffmpeg/factory/ffmpeg_video_factory.cpp
    src/media/codec/backends/ffmpeg/runtime/ffmpeg_runtime.cpp
    src/media/codec/backends/ffmpeg/runtime/ffmpeg_runtime_diagnostics.cpp
    src/media/codec/backends/ffmpeg/runtime/ffmpeg_runtime_libraries.cpp
    src/media/codec/backends/ffmpeg/runtime/ffmpeg_runtime_symbols.cpp
    src/media/codec/openh264/openh264_binary_manager.cpp
    src/media/codec/openh264/openh264_staging_internal.cpp
    src/media/runtime/runtime_library.cpp
    src/common/logger_manager.cpp
    src/common/worker_object_shutdown.cpp
    src/security/runtime_environment.cpp
    src/security/owner_consent.cpp
    src/security/audit_logger.cpp
    src/security/audit_session.cpp
    src/security/terminal_command_audit_parser.cpp
    src/security/terminal_command_log.cpp
    src/security/controlled_access_gate.cpp
    src/security/notification_script_runner.cpp
    src/util/qt/qt_callback_util.cpp
    src/main.cpp
    src/terminal/emulator/core/native_terminal_widget_callbacks.cpp
    src/terminal/emulator/terminal_emulator_worker.cpp
    src/terminal/emulator/input/native_terminal_widget_clipboard.cpp
    src/terminal/emulator/core/native_terminal_widget_core.cpp
    src/terminal/emulator/core/native_terminal_widget_helpers.cpp
    src/terminal/emulator/input/native_terminal_widget_input.cpp
    src/terminal/emulator/core/native_terminal_widget_io.cpp
    src/terminal/emulator/input/native_terminal_widget_mouse.cpp
    src/terminal/emulator/input/native_terminal_widget_selection.cpp
    src/terminal/file_panel/actions/terminal_file_panel_actions.cpp
    src/terminal/file_panel/terminal_file_panel_actions.cpp
    src/terminal/file_panel/terminal_file_panel.cpp
    src/terminal/file_panel/remote/terminal_file_panel_remote_mounts.cpp
    src/terminal/file_panel/remote/terminal_file_panel_remote_paths.cpp
    src/terminal/file_panel/remote/terminal_file_panel_remote.cpp
    src/terminal/file_panel/remote/terminal_file_panel_remote_table.cpp
    src/terminal/file_panel/terminal_file_panel_signals.cpp
    src/terminal/file_panel/view/terminal_file_panel_style.cpp
    src/terminal/file_panel/view/terminal_file_panel_table_ui.cpp
    src/terminal/file_panel/view/terminal_file_panel_toolbar.cpp
    src/terminal/file_panel/view/terminal_file_panel_ui.cpp
    src/terminal/emulator/core/native_terminal_widget.cpp
    src/terminal/emulator/render/native_terminal_widget_render.cpp
    src/terminal/session/terminal_session_control.cpp
    src/terminal/session/terminal_session.cpp
    src/terminal/session/terminal_session_fallback.cpp
    src/terminal/session/terminal_session_unix_pty.cpp
    src/terminal/session/terminal_session_windows_encoding.cpp
    src/terminal/session/terminal_session_windows_input.cpp
    src/terminal/session/terminal_session_windows_io.cpp
    src/terminal/session/terminal_session_windows_log.cpp
    src/terminal/session/terminal_session_windows_pty.cpp
    src/ui/chrome/app_title_bar.cpp
    src/ui/chrome/app_title_bar_drag.cpp
    src/ui/chrome/app_title_bar_icons.cpp
    src/ui/chrome/app_title_bar_resize.cpp
    src/ui/chrome/app_title_bar_style.cpp
    src/ui/chrome/app_title_bar_window.cpp
    src/ui/control/actions/control_window_audio_actions.cpp
    src/ui/control/actions/control_window_commands.cpp
    src/ui/control/control_window.cpp
    src/ui/control/input/control_window_input_keyboard.cpp
    src/ui/control/input/control_window_input_mouse_drag.cpp
    src/ui/control/input/control_window_input_mouse.cpp
    src/ui/control/actions/control_window_actions.cpp
    src/ui/control/android/control_window_android.cpp
    src/ui/control/connection/control_window_connection_progress.cpp
    src/ui/control/connection/control_window_connection_progress_parse.cpp
    src/ui/control/connection/control_window_connection_progress_render.cpp
    src/ui/control/control_window_events.cpp
    src/ui/control/android/control_window_android_side_panel.cpp
    src/ui/control/control_window_layout.cpp
    src/ui/control/actions/control_window_network_display.cpp
    src/ui/control/actions/control_window_remote_commands.cpp
    src/ui/control/control_window_rtc.cpp
    src/ui/control/control_window_state.cpp
    src/ui/control/toolbar/control_window_toolbar_buttons.cpp
    src/ui/control/toolbar/control_window_toolbar.cpp
    src/ui/control/toolbar/control_window_toolbar_helpers.cpp
    src/ui/control/toolbar/control_window_toolbar_layout_mode.cpp
    src/ui/control/toolbar/control_window_toolbar_modes.cpp
    src/ui/control/control_window_ui.cpp
    src/ui/control/video/control_window_video.cpp
    src/ui/control/video/control_window_video_cpu.cpp
    src/ui/control/video/control_window_video_layout.cpp
    src/ui/control/video/control_window_video_widgets.cpp
    src/ui/transfer/actions/file_transfer_window_actions.cpp
    src/ui/transfer/browser/file_transfer_window_browser.cpp
    src/ui/transfer/actions/file_transfer_window_download_actions.cpp
    src/ui/transfer/browser/file_transfer_window_local.cpp
    src/ui/transfer/remote/file_transfer_window_remote.cpp
    src/ui/transfer/remote/file_transfer_window_remote_paths.cpp
    src/ui/transfer/remote/file_transfer_window_remote_table.cpp
    src/ui/transfer/rtc/file_transfer_window_rtc.cpp
    src/ui/transfer/rtc/file_transfer_window_run.cpp
    src/ui/transfer/view/file_transfer_window_tables.cpp
    src/ui/transfer/task/file_transfer_window_task_model.cpp
    src/ui/transfer/task/file_transfer_window_task_state.cpp
    src/ui/transfer/task/file_transfer_window_task_ui.cpp
    src/ui/transfer/rtc/file_transfer_window_transfer_events.cpp
    src/ui/transfer/file_transfer_window.cpp
    src/ui/transfer/actions/file_transfer_window_upload_actions.cpp
    src/ui/transfer/view/file_transfer_window_ui.cpp
    src/ui/main/client/main_window_client.cpp
    src/ui/main/connection/main_window_connect_actions.cpp
    src/ui/main/main_window.cpp
    src/ui/main/events/main_window_events.cpp
    src/ui/main/layout/main_window_layout_actions.cpp
    src/ui/main/layout/main_window_layout_fields.cpp
    src/ui/main/layout/main_window_layout_labels.cpp
    src/ui/main/layout/main_window_layout.cpp
    src/ui/main/layout/main_window_layout_metrics.cpp
    src/ui/main/layout/main_window_layout_radios.cpp
    src/ui/main/layout/main_window_scale.cpp
    src/ui/main/session/main_window_sessions.cpp
    src/ui/main/share/main_window_share.cpp
    src/ui/main/setup/main_window_ui.cpp
    src/ui/main/websocket/main_window_ws.cpp
    src/ui/main/websocket/main_window_ws_connection.cpp
    src/ui/main/websocket/main_window_ws_errors.cpp
    src/ui/main/websocket/main_window_ws_messages.cpp
    src/ui/main/websocket/main_window_ws_sessions.cpp
    src/ui/widgets/password/password_line_edit_util_icons.cpp
    src/ui/widgets/password/password_line_edit_util.cpp
    src/ui/widgets/password/password_line_edit_util_state.cpp
    src/ui/settings/audio/settings_audio_backend.cpp
    src/ui/settings/audio/settings_audio_backend_fallback.cpp
    src/ui/settings/audio/settings_audio_backend_linux.cpp
    src/ui/settings/audio/settings_audio_backend_macos.cpp
    src/ui/settings/audio/settings_audio_backend_win.cpp
    src/ui/settings/audio/settings_audio_backend_win_common.cpp
    src/ui/settings/audio/settings_audio_backend_win_devices.cpp
    src/ui/settings/audio/settings_audio_backend_win_mic.cpp
    src/ui/settings/audio/settings_audio_backend_win_tone.cpp
    src/ui/settings/window/settings_window.cpp
    src/ui/settings/window/settings_window_about.cpp
    src/ui/settings/window/settings_window_audio.cpp
    src/ui/settings/window/settings_window_config.cpp
    src/ui/settings/window/settings_window_codecs.cpp
    src/ui/settings/window/settings_window_licenses.cpp
    src/ui/settings/licenses/license_catalog.cpp
    src/ui/settings/licenses/license_viewer_dialog.cpp
    src/ui/settings/window/settings_window_controls.cpp
    src/ui/settings/window/settings_window_geometry.cpp
    src/ui/settings/window/settings_window_service.cpp
    src/ui/settings/window/settings_window_notification.cpp
    src/ui/terminal/terminal_log_util.cpp
    src/ui/terminal/terminal_log_writer.cpp
    src/ui/terminal/terminal_window.cpp
    src/ui/terminal/terminal_window_events.cpp
    src/ui/terminal/terminal_window_log.cpp
    src/ui/terminal/terminal_window_protocol.cpp
    src/ui/terminal/terminal_window_rtc.cpp
    src/ui/terminal/terminal_window_ui.cpp
    src/ui/video/video_cpu_render_util.cpp
    src/util/config/config_util.cpp
    src/util/config/config_settings_writer.cpp
    src/util/config/config_util_codec.cpp
    src/util/config/config_util_common.cpp
    src/util/config/config_util_identity.cpp
    src/util/config/identity_storage.cpp
    src/util/config/config_util_paths.cpp
    src/util/text/convert_util.cpp
    src/util/file/core/file_packet_util.cpp
    src/util/file/core/file_packet_util_cancel.cpp
    src/util/file/read/file_packet_util_file.cpp
    src/util/file/write/file_packet_util_file_writer.cpp
    src/util/file/read/file_packet_util_receive.cpp
    src/util/file/read/file_packet_util_reassembly.cpp
    src/util/file/send/file_packet_util_send.cpp
    src/util/file/send/file_packet_util_send_backpressure.cpp
    src/util/file/send/file_packet_util_send_stream.cpp
    src/util/file/stream/file_packet_util_stream_helpers.cpp
    src/util/clipboard/clipboard_image_codec.cpp
    src/util/clipboard/clipboard_util.cpp
    src/util/text/i18n_util.cpp
    src/util/input/input_util_android.cpp
    src/util/input/input_util.cpp
    src/util/input/input_util_program.cpp
    src/util/input/input_util_remote_ops.cpp
    src/util/json/json_object_builder.cpp
    src/util/json/json_util_access.cpp
    src/util/json/json_util.cpp
    src/util/json/json_util_parse.cpp
    src/util/json/json_util_serialize.cpp
    src/rtc/core/rtc_data_channel.cpp
    src/rtc/media/codec/preferences/rtc_codec_preference_local_rank.cpp
    src/rtc/media/codec/preferences/rtc_codec_preferences.cpp
    src/rtc/media/codec/preferences/rtc_codec_preference_ranking.cpp
    src/rtc/media/codec/preferences/rtc_codec_preference_remote_score.cpp
    src/rtc/media/capture/airan_desktop_capture_source.cpp
    src/rtc/media/capture/rtc_desktop_video_source_select.cpp
    src/rtc/media/capture/rtc_desktop_video_sender.cpp
    src/rtc/core/rtc_frame_conversion.cpp
    src/rtc/core/rtc_internal.cpp
    src/rtc/peer/core/rtc_peer_connection.cpp
    src/rtc/peer/async/rtc_peer_connection_async_helpers.cpp
    src/rtc/peer/media/rtc_peer_connection_audio_track.cpp
    src/rtc/peer/signaling/rtc_peer_connection_codec_preferences.cpp
    src/rtc/peer/core/rtc_peer_connection_config.cpp
    src/rtc/peer/data/rtc_peer_connection_data_channels.cpp
    src/rtc/peer/factory/rtc_peer_connection_factory_helpers.cpp
    src/rtc/peer/factory/rtc_peer_connection_factories.cpp
    src/rtc/peer/factory/rtc_shared_audio_device_module.cpp
    src/rtc/peer/core/rtc_peer_connection_lifecycle.cpp
    src/rtc/peer/media/rtc_peer_connection_media_stats.cpp
    src/rtc/peer/core/rtc_peer_connection_observer.cpp
    src/rtc/peer/signaling/rtc_peer_connection_signaling.cpp
    src/rtc/peer/media/rtc_peer_connection_video_track.cpp
    src/rtc/signaling/rtc_sdp_simulcast_answer.cpp
    src/rtc/signaling/rtc_sdp_video_util.cpp
    src/rtc/core/rtc_runtime.cpp
    src/rtc/signaling/rtc_sdp_conversion.cpp
    src/rtc/core/rtc_track.cpp
    src/rtc/core/rtc_track_frames.cpp
    src/rtc/media/codec/factory/rtc_video_decoder_factory.cpp
    src/rtc/media/codec/factory/rtc_video_encoder_factory.cpp
    src/webrtc/cli/channel/webrtc_cli_channels.cpp
    src/webrtc/cli/channel/webrtc_cli_clipboard_channel.cpp
    src/webrtc/audio/system_audio_loopback_worker_linux.cpp
    src/webrtc/audio/system_audio_loopback_worker.cpp
    src/webrtc/audio/system_audio_loopback_worker_fallback.cpp
    src/webrtc/audio/system_audio_loopback_worker_mixer.cpp
    src/webrtc/audio/system_audio_loopback_worker_win.cpp
    src/webrtc/codec/video_codec_capability_signaling.cpp
    src/webrtc/cli/media/webrtc_cli_audio.cpp
    src/webrtc/cli/control/webrtc_cli_control.cpp
    src/webrtc/cli/control/webrtc_cli_stream_control.cpp
    src/webrtc/cli/lifecycle/webrtc_cli_cleanup.cpp
    src/webrtc/cli/lifecycle/webrtc_cli_session_shutdown.cpp
    src/webrtc/cli/file_transfer/webrtc_cli_files.cpp
    src/webrtc/cli/input/webrtc_cli_input_dispatch.cpp
    src/webrtc/cli/lifecycle/webrtc_cli_lifecycle.cpp
    src/webrtc/cli/lifecycle/webrtc_cli_session_heartbeat.cpp
    src/webrtc/cli/signaling/webrtc_cli_signaling.cpp
    src/webrtc/cli/file_transfer/webrtc_cli_file_transfer.cpp
    src/webrtc/cli/file_transfer/webrtc_cli_file_transfer_receive.cpp
    src/webrtc/cli/file_transfer/webrtc_cli_file_transfer_send.cpp
    src/webrtc/cli/file_transfer/webrtc_cli_file_transfer_send_directory.cpp
    src/webrtc/cli/file_transfer/webrtc_cli_file_transfer_send_single.cpp
    src/webrtc/cli/channel/webrtc_cli_channel_send.cpp
    src/webrtc/cli/input/webrtc_cli_input_channels.cpp
    src/webrtc/cli/media/webrtc_cli_media_labels.cpp
    src/webrtc/cli/media/webrtc_cli_media_stats.cpp
    src/webrtc/cli/media/webrtc_cli_capture_state.cpp
    src/webrtc/cli/peer/webrtc_cli_peer.cpp
    src/webrtc/cli/peer/webrtc_cli_peer_configuration.cpp
    src/webrtc/cli/peer/webrtc_cli_peer_remote.cpp
    src/webrtc/cli/peer/webrtc_cli_peer_setup.cpp
    src/webrtc/cli/peer/webrtc_cli_peer_signaling.cpp
    src/webrtc/cli/peer/webrtc_cli_peer_state.cpp
    src/webrtc/cli/peer/webrtc_cli_senders.cpp
    src/webrtc/cli/control/webrtc_cli_stream_state.cpp
    src/webrtc/cli/terminal/webrtc_cli_terminal.cpp
    src/webrtc/cli/media/webrtc_cli_video_send.cpp
    src/webrtc/ctl/lifecycle/webrtc_ctl_cleanup.cpp
    src/webrtc/ctl/lifecycle/webrtc_ctl_control_heartbeat.cpp
    src/webrtc/ctl/media/webrtc_ctl_audio.cpp
    src/webrtc/ctl/lifecycle/webrtc_ctl_lifecycle.cpp
    src/webrtc/ctl/lifecycle/webrtc_ctl_session_heartbeat.cpp
    src/webrtc/ctl/peer/webrtc_ctl_peer.cpp
    src/webrtc/ctl/signaling/webrtc_ctl_peer_signaling.cpp
    src/webrtc/ctl/peer/webrtc_ctl_peer_state.cpp
    src/webrtc/ctl/peer/webrtc_ctl_peer_tracks.cpp
    src/webrtc/ctl/peer/webrtc_ctl_remote_data_channel.cpp
    src/webrtc/ctl/peer/webrtc_ctl_remote_track.cpp
    src/webrtc/ctl/lifecycle/webrtc_ctl_reconnect.cpp
    src/webrtc/ctl/signaling/webrtc_ctl_remote_signaling.cpp
    src/webrtc/ctl/signaling/webrtc_ctl_signaling.cpp
    src/webrtc/ctl/channel/webrtc_ctl_channel_setup.cpp
    src/webrtc/ctl/channel/webrtc_ctl_channels.cpp
    src/webrtc/ctl/channel/webrtc_ctl_channel_send.cpp
    src/webrtc/ctl/channel/webrtc_ctl_file_channel.cpp
    src/webrtc/ctl/file_transfer/webrtc_ctl_file_transfer.cpp
    src/webrtc/ctl/file_transfer/webrtc_ctl_file_transfer_send.cpp
    src/webrtc/ctl/file_transfer/webrtc_ctl_file_transfer_send_directory.cpp
    src/webrtc/ctl/file_transfer/webrtc_ctl_file_transfer_send_single.cpp
    src/webrtc/ctl/file_transfer/webrtc_ctl_file_transfer_state.cpp
    src/webrtc/ctl/channel/webrtc_ctl_file_text_channel.cpp
    src/webrtc/ctl/channel/webrtc_ctl_clipboard_channel.cpp
    src/webrtc/ctl/channel/webrtc_ctl_file_text_terminal.cpp
    src/webrtc/ctl/channel/webrtc_ctl_file_text_transfer.cpp
    src/webrtc/ctl/input/webrtc_ctl_input_channel.cpp
    src/webrtc/ctl/input/webrtc_ctl_input_send.cpp
    src/webrtc/ctl/media/webrtc_ctl_media.cpp
    src/webrtc/ctl/network/webrtc_ctl_network.cpp
    src/webrtc/ctl/network/webrtc_ctl_network_path.cpp
    src/webrtc/ctl/network/webrtc_ctl_network_path_util.cpp
    src/webrtc/ctl/media/webrtc_ctl_stream_config.cpp
    src/webrtc/ctl/peer/webrtc_ctl_peer_state_text.cpp
    src/websocket/ws_cli.cpp
    src/websocket/signaling_url_resolver.cpp
    src/websocket/ws_cli_events.cpp
    src/websocket/ws_cli_messages.cpp
    src/websocket/ws_cli_reconnect.cpp
)

set(HDR_FILES
    src/app/app_runtime.h
    src/app/app_runtime_internal.h
    src/app/app_headless_controller.h
    src/app/app_style.h
    src/media/codec/webrtc/airan_codec_adapter.h
    src/media/capture/core/airan_capture_frame.h
    src/media/capture/core/airan_capture_interface.h
    src/media/codec/airan_video_codec_backend.h
    src/media/codec/backends/ffmpeg/codec/ffmpeg_codec_probe.h
    src/media/codec/backends/ffmpeg/codec/ffmpeg_codec_probe_internal.h
    src/media/codec/backends/ffmpeg/codec/ffmpeg_codec_types.h
    src/media/codec/backends/ffmpeg/codec/ffmpeg_openh264_option.h
    src/media/codec/backends/ffmpeg/decoder/ffmpeg_video_decoder.h
    src/media/codec/backends/ffmpeg/encoder/core/ffmpeg_video_encoder.h
    src/media/codec/backends/ffmpeg/encoder/util/ffmpeg_encoder_util.h
    src/media/codec/backends/ffmpeg/factory/ffmpeg_video_factory.h
    src/media/codec/backends/ffmpeg/runtime/ffmpeg_runtime.h
    src/media/codec/openh264/openh264_binary_manager.h
    src/media/codec/openh264/openh264_release_manifest.h
    src/media/codec/openh264/openh264_staging_internal.h
    src/media/runtime/runtime_library.h
    src/common/constant.h
    src/common/date_size_file_sink.h
    src/common/logger_manager.h
    src/common/worker_object_shutdown.h
    src/security/runtime_environment.h
    src/security/owner_consent.h
    src/security/audit_logger.h
    src/security/audit_session.h
    src/security/terminal_command_audit_parser.h
    src/security/terminal_command_log.h
    src/security/controlled_access_gate.h
    src/security/notification_script_runner.h
    src/common/object_lifecycle.h
    src/common/platform_headers.h
    src/common/protocol_constants.h
    src/common/qt_rtc_metatypes.h
    src/util/qt/qt_callback_util.h
    src/terminal/file_panel/terminal_file_panel.h
    src/terminal/emulator/native_terminal_widget_colors.h
    src/terminal/emulator/native_terminal_widget.h
    src/terminal/emulator/terminal_emulator_worker.h
    src/terminal/session/terminal_session.h
    src/ui/chrome/app_title_bar.h
    src/ui/chrome/app_title_bar_icons.h
    src/ui/common/adaptive_ui.h
    src/ui/control/control_window.h
    src/ui/control/connection/control_window_connection_progress_state.h
    src/ui/control/control_window_view_helpers.h
    src/ui/transfer/file_transfer_window.h
    src/ui/main/main_window.h
    src/ui/main/layout/main_window_layout_metrics.h
    src/ui/widgets/password/password_line_edit_util.h
    src/ui/widgets/password/password_line_edit_util_internal.h
    src/ui/settings/audio/settings_audio_backend.h
    src/ui/settings/audio/settings_audio_backend_internal.h
    src/ui/settings/audio/settings_audio_backend_win_common.h
    src/ui/settings/window/settings_window.h
    src/ui/settings/licenses/license_catalog.h
    src/ui/settings/licenses/license_viewer_dialog.h
    src/ui/terminal/terminal_log_util.h
    src/ui/terminal/terminal_log_writer.h
    src/ui/terminal/terminal_window.h
    src/ui/video/video_cpu_render_util.h
    src/util/config/config_util.h
    src/util/config/config_settings_writer.h
    src/util/config/identity_storage.h
    src/util/config/config_util_codec.h
    src/util/config/config_util_paths.h
    src/util/text/convert_util.h
    src/util/file/file_packet_util.h
    src/util/file/stream/file_packet_util_stream_helpers.h
    src/util/clipboard/clipboard_image_codec.h
    src/util/clipboard/clipboard_util.h
    src/util/clipboard/native/clipboard_file_promise.h
    src/util/text/i18n_util.h
    src/util/input/input_util.h
    src/util/input/platform/linux/input_util_events_linux_internal.h
    src/util/json/json_util.h
    src/util/input/key_util.h
    src/rtc/core/rtc.hpp
    src/rtc/core/rtc_base_types.h
    src/rtc/core/rtc_data_channel.h
    src/rtc/core/rtc_media_types.h
    src/rtc/core/rtc_peer_connection.h
    src/rtc/core/rtc_signaling_types.h
    src/rtc/core/rtc_track.h
    src/rtc/media/codec/preferences/rtc_codec_preference_ranking.h
    src/rtc/media/codec/preferences/rtc_codec_preference_ranking_internal.h
    src/rtc/media/capture/airan_desktop_capture_source.h
    src/rtc/media/capture/rtc_desktop_video_source_select.h
    src/rtc/core/rtc_internal.h
    src/rtc/peer/async/rtc_peer_connection_async_helpers.h
    src/rtc/peer/factory/rtc_peer_connection_factory_helpers.h
    src/rtc/peer/factory/rtc_peer_connection_factories.h
    src/rtc/peer/factory/rtc_shared_audio_device_module.h
    src/rtc/peer/media/rtc_peer_connection_media_helpers.h
    src/rtc/signaling/rtc_sdp_simulcast_answer.h
    src/rtc/signaling/rtc_sdp_video_util.h
    src/rtc/core/d3d11_video_frame.h
    src/rtc/core/native_d3d11_video_frame_buffer.h
    src/webrtc/cli/webrtc_cli.h
    src/webrtc/cli/lifecycle/webrtc_cli_session_shutdown.h
    src/webrtc/cli/media/webrtc_cli_media_labels.h
    src/webrtc/audio/system_audio_loopback_worker.h
    src/webrtc/codec/video_codec_capability_signaling.h
    src/media/codec/airan_video_bitrate_profile.h
    src/webrtc/ctl/webrtc_ctl.h
    src/webrtc/ctl/network/webrtc_ctl_network_path_util.h
    src/webrtc/ctl/peer/webrtc_ctl_peer_state_text.h
    src/websocket/ws_cli.h
    src/websocket/signaling_url_resolver.h
)

set(UI_FILES
    src/ui/control/control_window.ui
    src/ui/transfer/file_transfer_window.ui
    src/ui/main/main_window.ui
    src/ui/settings/window/settings_window.ui
    src/ui/terminal/terminal_window.ui
)

set(RESOURCE_FILES
    resource/qt/resources.qrc
)

set(TS_FILES
    resource/locale/airan-desk_zh_CN.ts
    resource/locale/airan-desk_en_US.ts
)

list(APPEND SRC_FILES
    src/desktop_capture/blank_detector_desktop_capturer_wrapper.cc
    src/desktop_capture/cropped_desktop_frame.cc
    src/desktop_capture/desktop_and_cursor_composer.cc
    src/desktop_capture/desktop_capture_metrics_helper.cc
    src/desktop_capture/desktop_capture_options.cc
    src/desktop_capture/desktop_capturer.cc
    src/desktop_capture/desktop_capturer_differ_wrapper.cc
    src/desktop_capture/desktop_capturer_wrapper.cc
    src/desktop_capture/desktop_frame.cc
    src/desktop_capture/desktop_frame_rotation.cc
    src/desktop_capture/desktop_geometry.cc
    src/desktop_capture/desktop_region.cc
    src/desktop_capture/differ_block.cc
    src/desktop_capture/fallback_desktop_capturer_wrapper.cc
    src/desktop_capture/full_screen_application_handler.cc
    src/desktop_capture/full_screen_window_detector.cc
    src/desktop_capture/mouse_cursor.cc
    src/desktop_capture/resolution_tracker.cc
    src/desktop_capture/rgba_color.cc
    src/desktop_capture/screen_capturer_helper.cc
    src/desktop_capture/shared_desktop_frame.cc
    src/desktop_capture/shared_memory.cc
    src/desktop_capture/window_finder.cc
)

# differ_vector_sse2.cc 使用 SSE2 intrinsics，仅在 x86/x86_64 目标平台编译
# 注意：VS ARM64 交叉编译时 CMAKE_SYSTEM_PROCESSOR 仍报告为 AMD64（宿主机），
# 需同时排除 CMAKE_GENERATOR_PLATFORM 为 ARM/ARM64 的情况
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|x86|i[3-6]86|AMD64|amd64)$" AND
   NOT CMAKE_GENERATOR_PLATFORM MATCHES "^(ARM|ARM64|ARM64EC)$")
    list(APPEND SRC_FILES src/desktop_capture/differ_vector_sse2.cc)
endif()

if(WIN32)
    list(APPEND SRC_FILES
        src/desktop_capture/cropping_window_capturer.cc
        src/desktop_capture/cropping_window_capturer_win.cc
        src/desktop_capture/desktop_frame_win.cc
        src/desktop_capture/mouse_cursor_monitor_win.cc
        src/desktop_capture/screen_capturer_win.cc
        src/desktop_capture/window_capturer_win.cc
        src/desktop_capture/window_finder_win.cc
        src/desktop_capture/win/cursor.cc
        src/desktop_capture/win/desktop.cc
        src/desktop_capture/win/desktop_capture_utils.cc
        src/desktop_capture/win/display_configuration_monitor.cc
        src/desktop_capture/win/full_screen_win_application_handler.cc
        src/desktop_capture/win/scoped_thread_desktop.cc
        src/desktop_capture/win/screen_capture_utils.cc
        src/desktop_capture/win/screen_capturer_win_gdi.cc
        src/desktop_capture/win/screen_capturer_win_magnifier.cc
        src/desktop_capture/win/selected_window_context.cc
        src/desktop_capture/win/window_capture_utils.cc
        src/desktop_capture/win/window_capturer_win_gdi.cc
        src/util/clipboard/native/clipboard_file_promise_win.cpp
    )
    if(NOT LIBWEBRTC_PLATFORM STREQUAL "win7")
        list(APPEND SRC_FILES
            src/ui/control/video/control_window_video_d3d11.cpp
            src/ui/video/d3d11_video_widget.cpp
            src/ui/video/d3d11_video_widget_render.cpp
            src/ui/video/d3d11_video_widget_shaders.cpp
            src/ui/video/d3d11_video_widget_swapchain.cpp
            src/desktop_capture/win/d3d_device.cc
            src/desktop_capture/win/dxgi_adapter_duplicator.cc
            src/desktop_capture/win/dxgi_context.cc
            src/desktop_capture/win/dxgi_duplicator_controller.cc
            src/desktop_capture/win/dxgi_frame.cc
            src/desktop_capture/win/dxgi_output_duplicator.cc
            src/desktop_capture/win/dxgi_texture.cc
            src/desktop_capture/win/dxgi_texture_mapping.cc
            src/desktop_capture/win/dxgi_texture_staging.cc
            src/desktop_capture/win/screen_capturer_win_directx.cc
            src/desktop_capture/win/wgc_capture_session.cc
            src/desktop_capture/win/wgc_capture_source.cc
            src/desktop_capture/win/wgc_capturer_win.cc
            src/desktop_capture/win/wgc_desktop_frame.cc
        )
        list(APPEND HEADER_FILES
            src/ui/video/d3d11_video_widget.h
        )
    endif()
elseif(APPLE)
    list(APPEND SRC_FILES
        src/desktop_capture/mouse_cursor_monitor_mac.mm
        src/desktop_capture/screen_capturer_darwin.mm
        src/desktop_capture/window_capturer_mac.mm
        src/desktop_capture/window_finder_mac.mm
        src/desktop_capture/mac/desktop_configuration.mm
        src/desktop_capture/mac/desktop_configuration_monitor.cc
        src/desktop_capture/mac/desktop_frame_cgimage.mm
        src/desktop_capture/mac/desktop_frame_iosurface.mm
        src/desktop_capture/mac/desktop_frame_provider.mm
        src/desktop_capture/mac/desktop_frame_utils.cc
        src/desktop_capture/mac/full_screen_mac_application_handler.cc
        src/desktop_capture/mac/sck_picker_handle.mm
        src/desktop_capture/mac/screen_capturer_mac.mm
        src/desktop_capture/mac/screen_capturer_sck.mm
        src/desktop_capture/mac/window_list_utils.cc
        src/util/clipboard/native/clipboard_file_promise_macos.mm
    )
elseif(UNIX)
    list(APPEND SRC_FILES
        src/desktop_capture/mouse_cursor_monitor_linux.cc
        src/desktop_capture/screen_capturer_linux.cc
        src/desktop_capture/window_capturer_linux.cc
        src/desktop_capture/linux/x11/mouse_cursor_monitor_x11.cc
        src/desktop_capture/linux/x11/screen_capturer_x11.cc
        src/desktop_capture/linux/x11/shared_x_display.cc
        src/desktop_capture/linux/x11/window_capturer_x11.cc
        src/desktop_capture/linux/x11/window_finder_x11.cc
        src/desktop_capture/linux/x11/window_list_utils.cc
        src/desktop_capture/linux/x11/x_atom_cache.cc
        src/desktop_capture/linux/x11/x_error_trap.cc
        src/desktop_capture/linux/x11/x_server_pixel_buffer.cc
        src/desktop_capture/linux/x11/x_window_property.cc
        src/util/clipboard/native/clipboard_file_promise_linux.cpp
    )
    if(AIRAN_ENABLE_PIPEWIRE_CAPTURE)
        list(APPEND SRC_FILES
            src/desktop_capture/linux/wayland/base_capturer_pipewire.cc
            src/desktop_capture/linux/wayland/egl_dmabuf.cc
            src/desktop_capture/linux/wayland/mouse_cursor_monitor_pipewire.cc
            src/desktop_capture/linux/wayland/pipewire_utils.cc
            src/desktop_capture/linux/wayland/restore_token_manager.cc
            src/desktop_capture/linux/wayland/scoped_glib.cc
            src/desktop_capture/linux/wayland/screen_capture_portal_interface.cc
            src/desktop_capture/linux/wayland/screencast_portal.cc
            src/desktop_capture/linux/wayland/screencast_stream_utils.cc
            src/desktop_capture/linux/wayland/shared_screencast_stream.cc
            src/desktop_capture/linux/wayland/xdg_desktop_portal_utils.cc
        )
    endif()
else()
    list(APPEND SRC_FILES
        src/desktop_capture/mouse_cursor_monitor_null.cc
        src/desktop_capture/screen_capturer_null.cc
        src/desktop_capture/window_capturer_null.cc
        src/util/clipboard/native/clipboard_file_promise_fallback.cpp
    )
endif()
